spring.application.name=HBS
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/HBS
spring.datasource.username=anant
spring.datasource.password=ANANT@123a
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=anant8139@gmail.com
spring.mail.password=mfyd atxu bepo hesg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true